#!/usr/bin/env python3
"""Gzip the portal's static assets into src/web/web_assets.h.

The panel serves the portal out of loop(), so the picture stands still while a
browser is pulling it. portal.js is ~44 KB and portal.css ~23 KB of flash, sent
as plain text. Gzipped they are a third of that, and the browser unpacks them
for free.

The sources stay where they are - the raw strings in src/web/web_pages.h - so
editing the portal does not change: this only rewrites the generated header.

  python3 tools/web_assets_gen.py           # regenerate
  python3 tools/web_assets_gen.py --check   # exit 1 if web_assets.h is stale

The build runs --check (platformio.ini, extra_scripts), so a header that no
longer matches its source fails the build instead of shipping a page that
disagrees with the repository.

Each asset also gets a short content hash, and the page's ?v= query uses it, so
a browser keeps a cached copy for as long as the bytes stay the same and fetches
a new one the moment they change.

The gzip carries no file name and mtime 0. A rerun keeps a blob that still
decompresses to its source, so gzip from another Python on another machine
neither rewrites the header nor makes --check call it stale.
"""

import gzip, hashlib, io, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB = ROOT / "src/web"
OUT = WEB / "web_assets.h"

# (C variable in web_pages.h, name in the generated header, what it is served as)
ASSETS = [
    ("PORTAL_CSS", "PORTAL_CSS_GZ", "/portal.css"),
    ("PORTAL_JS", "PORTAL_JS_GZ", "/portal.js"),
    ("FAVICON_SVG", "FAVICON_SVG_GZ", "/favicon.svg"),
]


def source_text(text, var):
    """The text of `static const char VAR[] PROGMEM = R"d(...)d"`, as the compiler sees it."""
    raw = re.search(r'\b%s\[\]\s*PROGMEM\s*=\s*R"(\w*)\((.*?)\)\1"' % var, text, re.S)
    if not raw:
        raise SystemExit(f"web_assets_gen: no raw string {var} in src/web/web_pages.h")
    return raw[2]


def deflate(data):
    buf = io.BytesIO()
    # mtime 0 and no file name: the same bytes on every machine.
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
        gz.write(data)
    return buf.getvalue()


def c_array(name, blob):
    lines = [f"static const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(blob), 16):
        row = ", ".join("0x%02x" % b for b in blob[i:i + 16])
        lines.append(f"  {row},")
    lines.append("};")
    return "\n".join(lines)


def previous_blob(text, name):
    """The blob already in the header, so an identical asset is not rewritten."""
    m = re.search(r"static const uint8_t %s\[\] PROGMEM = \{(.*?)\};" % name, text, re.S)
    if not m:
        return None
    return bytes(int(b, 16) for b in re.findall(r"0x([0-9a-f]{2})", m[1]))


def build():
    old = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    pages = (WEB / "web_pages.h").read_text(encoding="utf-8")
    parts = [
        "// Generated by tools/web_assets_gen.py - do not edit.",
        "//",
        "// The portal's static assets, gzipped. Sources: the raw strings in",
        "// web_pages.h. Rerun the generator after changing them; the build checks.",
        "",
        "#ifndef WEB_ASSETS_H",
        "#define WEB_ASSETS_H",
        "",
        "#include <Arduino.h>",
        "",
    ]
    report = []
    digest = hashlib.sha256()
    for var, name, url in ASSETS:
        raw = source_text(pages, var).encode("utf-8")
        blob = deflate(raw)
        kept = previous_blob(old, name)
        if kept is not None:
            try:
                if gzip.decompress(kept) == raw:
                    blob = kept  # another zlib, same source: leave the header alone
            except Exception:
                pass
        digest.update(hashlib.sha256(raw).digest())
        parts.append(f"// {url}: {len(raw):,} B source -> {len(blob):,} B gzip")
        parts.append(c_array(name, blob))
        parts.append("")
        report.append((url, len(raw), len(blob)))
    parts.append('#define WEB_ASSET_VERSION "%s"' % digest.hexdigest()[:12])
    parts.append("")
    parts.append("#endif // WEB_ASSETS_H")
    return "\n".join(parts) + "\n", report


def main():
    text, report = build()
    check = "--check" in sys.argv
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if check:
        if current == text:
            return 0
        print(f"web_assets_gen: src/web/web_assets.h is stale - run "
              f"`{sys.executable} tools/web_assets_gen.py` and commit the result.", file=sys.stderr)
        return 1
    # newline="\n": the header is committed, and CRLF would rewrite every line of it.
    with OUT.open("w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    for url, raw, blob in report:
        print(f"  {url:<14} {raw:>8,} B -> {blob:>7,} B ({blob * 100 // raw}%)")
    print(f"{OUT.relative_to(ROOT)}: {len(text):,} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
